//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_ProyectoDAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apoyos
    {
        public int id_Apoyo { get; set; }
        public int puebloOrigen { get; set; }
        public int puebloDestino { get; set; }
        public Nullable<int> arqueros { get; set; }
        public Nullable<int> ballesteros { get; set; }
        public Nullable<System.DateTime> horaFin { get; set; }
    
        public virtual Pueblo Pueblo { get; set; }
        public virtual Pueblo Pueblo1 { get; set; }
    }
}
