//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_ProyectoDAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int id_Movimiento { get; set; }
        public int puebloOrigen { get; set; }
        public int puebloDestino { get; set; }
        public string tipoMovimiento { get; set; }
        public System.TimeSpan duracion { get; set; }
        public System.DateTime horaLlegada { get; set; }
        public int arqueros { get; set; }
        public int ballesteros { get; set; }
        public int piqueros { get; set; }
        public int caballeros { get; set; }
        public int paladines { get; set; }
        public int vencedor { get; set; }
    
        public virtual Pueblo Pueblo { get; set; }
    }
}
