//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_ProyectoDAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenReclutamiento
    {
        public int idOrden { get; set; }
        public int pueblo { get; set; }
        public int tropa { get; set; }
        public Nullable<int> cantidad { get; set; }
        public System.DateTime horaFin { get; set; }
        public bool terminado { get; set; }
    
        public virtual Pueblo Pueblo1 { get; set; }
        public virtual Tropas Tropas { get; set; }
    }
}
