//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_ProyectoDAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pueblo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pueblo()
        {
            this.Apoyos = new HashSet<Apoyos>();
            this.Apoyos1 = new HashSet<Apoyos>();
            this.Movimientos = new HashSet<Movimientos>();
            this.Movimientos1 = new HashSet<Movimientos>();
        }
    
        public int id_Pueblo { get; set; }
        public string propietario { get; set; }
        public Nullable<int> poblacion { get; set; }
        public Nullable<int> arqueros { get; set; }
        public Nullable<int> ballesteros { get; set; }
        public Nullable<int> piqueros { get; set; }
        public Nullable<int> caballeros { get; set; }
        public Nullable<int> paladines { get; set; }
        public string coordenadas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apoyos> Apoyos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apoyos> Apoyos1 { get; set; }
        public virtual Jugador Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos1 { get; set; }
    }
}
